version: '3'

services:
  cacher:
    build:
      context: .
    restart: always
    volumes:
      - /tank/mirror/apt-cacher-ng:/var/cache/apt-cacher-ng
    extra_hosts:
        - "package-server:10.112.11.105"
    ports:
      - "3142:3142"
